name: â« Sync Updates
on:
  push:
    branches:
    - dev
    - alpha

jobs:
  alpha:
    runs-on: ubuntu-latest
    if: github.ref_name == 'dev'
    steps:
    - name: ğŸ’¾ Checkout
      uses: actions/checkout@v3
      with:
        ref: alpha

    - name: ğŸ›‘ Reset promotion branch
      run: |
        git fetch origin ${{github.ref_name}}:${{github.ref_name}}
        git reset --hard ${{github.ref_name}}

    - name: ğŸ†• Create Pull Request
      uses: peter-evans/create-pull-request@v5.0.2
      with:
        labels: automated pr
        branch: ${{github.ref_name}}
        title: chore(sync) Syncing changes from ${{github.ref_name}} to alpha

  main:
    runs-on: ubuntu-latest
    if: github.ref_name == 'alpha'
    steps:
    - name: ğŸ’¾ Checkout
      uses: actions/checkout@v3
      with:
        ref: main

    - name: ğŸ›‘ Reset promotion branch
      run: |
        git fetch origin ${{github.ref_name}}:${{github.ref_name}}
        git reset --hard ${{github.ref_name}}

    - name: ğŸ†• Create Pull Request
      uses: peter-evans/create-pull-request@v5.0.2
      with:
        labels: automated pr
        branch: ${{github.ref_name}}
        title: chore(sync) Syncing changes from ${{github.ref_name}} to main
